#!/bin/sh
set -e
. ./build.sh

mkdir -p isodir
mkdir -p isodir/boot
mkdir -p isodir/boot/grub

cp sysroot/boot/hexos.kernel isodir/boot/hexos.kernel
cat > isodir/boot/grub/grub.cfg << EOF
menuentry "HexOS (serial debug on COM1)" {
	multiboot /boot/hexos.kernel -serdbg
}
menuentry "HexOS" {
	multiboot /boot/hexos.kernel
}
insmod gfxmenu
set theme=\$prefix/themes/hexos/theme.txt
set menu_color_normal=dark-gray/blue
set menu_color_highlight=white/blue
export theme
EOF

mkdir -p isodir/boot/grub/themes/hexos/

cat > isodir/boot/grub/themes/hexos/theme.txt << EOF
title-text: "HexOS"
+ label { text="hex" font="aqui 11" color="#8FF" }
EOF

cat > isodir/test.txt << EOF
Hello!
This is a file used to verify that HexOS can read files!
yay!
:D
EOF

cat > isodir/long.txt << EOF
Hello!
This is a longer file used to verify that HexOS can read really large files!
This file should be longer than 2048 bytes.
hello hello there.
yay yay yay.
this is a FILE. random junk: kasdjfkaljdfklasjdclasdasdkfjaskdlfjaklsdfjalksdfjaoisdhfaiusbodfct3q2ierwlucbhg812937iequrybh982eqiowzng1872EUIRTB@Uio123euryhuidsOIYHoajfa9iudfhjnw98fohqewdoufichansdjkhausifge8uidfhads8KFHfdvvcxnznvgiadfbqwejfhqwiueOJdfhjnw98fohqewdoufichansdjkhausifge8uidfhads87fu3i4berfCWUDFIULJFKhofhqweuiftqiowuerhqiwfhiuohausiofjhbnashofdgaosyudfigbh2org132yrgfubeofadbf8wuidshfbiuwdjksafasdfeyodisubfyhcasuidfhcUIEdsauhfiusoadhfuiokjdfhuidhfuasihfasfijasfndiuasdhf98pieourxio123euryhuidsoajfa9iu7fu3i4berfweIEOJKFHCWUDOIYHFIULJFKhdsauhfiusoadhfuiokjdfhuidhfuasihfasfijasfndiuasdng1872EUIRTB@dhf98pieourxf8yer873ruiwdfhdsuiay78uiwhweffdvvcxnznvgiadfbqwejfhqwiueOJdfhjnw98fohqewdoufichansdjkhausifge8uidfhads87fu3i4berfaskdfjaskldfjaslkdjfkl;asfjkals;dfjioeruwklwjfioadsfuifohakfljasdfijasdfioasjfiosjdf
more junk: kasdjfkaljdfklasjdclasdasdkfjaskdlfjaklsdfjalksdfjaoisdhfaiusbodfct3q2ierwlucbhg812937iequrybh982eqiowzng1872EUIRTB@Uio123euryhuidsOIYHoajfa9iudfhjnw98fohqewdoufichansdjkhausifge8uidfhads8KFHfdvvcxnznvgiadfbqwejfhqwiueOJdfhjnw98fohqewdoufichansdjkhausifge8uidfhads87fu3i4berfCWUDFIULJFKhofhqweuiftqiowuerhqiwfhiuohausiofjhbnashofdgaosyudfigbh2org132yrgfubeofadbf8wuidshfbiuwdjksafasdfeyodisubfyhcasuidfhcUIEdsauhfiusoadhfuiokjdfhuidhfuasihfasfijasfndiuasdhf98pieourxio123euryhuidsoajfa9iu7fu3i4berfweIEOJKFHCWUDOIYHFIULJFKhdsauhfiusoadhfuiokjdfhuidhfuasihfasfijasfndiuasdng1872EUIRTB@dhf98pieourxf8yer873ruiwdfhdsuiay78uiwhweffdvvcxnznvgiadfbqwejfhqwiueOJdfhjnw98fohqewdoufichansdjkhausifge8uidfhads87fu3i4berfaskdfjaskldfjaslkdjfkl;asfjkals;dfjioeruwklwjfioadsfuifohakfljasdfijasdfioasjfiosjdf
and finally: kasdjfkaljdfklasjdclasdasdkfjaskdlfjaklsdfjalksdfjaoisdhfaiusbodfct3q2ierwlucbhg812937iequrybh982eqiowzng1872EUIRTB@Uio123euryhuidsOIYHoajfa9iudfhjnw98fohqewdoufichansdjkhausifge8uidfhads8KFHfdvvcxnznvgiadfbqwejfhqwiueOJdfhjnw98fohqewdoufichansdjkhausifge8uidfhads87fu3i4berfCWUDFIULJFKhofhqweuiftqiowuerhqiwfhiuohausiofjhbnashofdgaosyudfigbh2org132yrgfubeofadbf8wuidshfbiuwdjksafasdfeyodisubfyhcasuidfhcUIEdsauhfiusoadhfuiokjdfhuidhfuasihfasfijasfndiuasdhf98pieourxio123euryhuidsoajfa9iu7fu3i4berfweIEOJKFHCWUDOIYHFIULJFKhdsauhfiusoadhfuiokjdfhuidhfuasihfasfijasfndiuasdng1872EUIRTB@dhf98pieourxf8yer873ruiwdfhdsuiay78uiwhweffdvvcxnznvgiadfbqwejfhqwiueOJdfhjnw98fohqewdoufichansdjkhausifge8uidfhads87fu3i4berfaskdfjaskldfjaslkdjfkl;asfjkals;dfjioeruwklwjfioadsfuifohakfljasdfijasdfioasjfiosjdf

Some of that text up there is *supposed* to repeat. Yay, I think this is at 2048 bytes now. Finally!
EOF

grub-mkrescue -o hexos.iso isodir
